name: Projeto_Jarvis

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # --- Versão do Python ---
  - python=3.10

  # --- Pacotes Conda ---
  - pytorch
  - cpuonly # Adicione esta linha se você NÃO tem uma GPU NVIDIA. Remova se tiver.
  - pyaudio
  - scikit-learn
  - flask
  - requests
  - python-dotenv
  - pytest
  - huggingface-hub

  # --- Pacotes Pip ---
  - pip
  - pip:
    - pyttsx3
    - SpeechRecognition
    - sentence-transformers
    - flet
